/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ParaTodoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  masterTodoFilename: "_Master TODO List.md",
  paraFolders: ["_Projects", "_Areas", "_Resources", "_Archive"],
  todoNotePrefix: "_TODO - ",
  syncOnStartup: true,
  syncIntervalMinutes: 5
};

// src/settingsTab.ts
var import_obsidian = require("obsidian");
var ParaTodoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "PARA TODO Settings" });
    new import_obsidian.Setting(containerEl).setName("Master TODO filename").setDesc("The filename for the master TODO list (include .md extension)").addText((text) => text.setPlaceholder("_Master TODO List.md").setValue(this.plugin.settings.masterTodoFilename).onChange(async (value) => {
      this.plugin.settings.masterTodoFilename = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("PARA Folders").setDesc("Comma-separated list of root PARA folders to scan for TODO notes").addText((text) => text.setPlaceholder("_Projects,_Areas,_Resources,_Archive").setValue(this.plugin.settings.paraFolders.join(",")).onChange(async (value) => {
      this.plugin.settings.paraFolders = value.split(",").map((f) => f.trim());
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("TODO Note Prefix").setDesc("The prefix for individual TODO notes (will be followed by folder name)").addText((text) => text.setPlaceholder("_TODO - ").setValue(this.plugin.settings.todoNotePrefix).onChange(async (value) => {
      this.plugin.settings.todoNotePrefix = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync on Startup").setDesc("Automatically sync TODOs when Obsidian starts").addToggle((toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
      this.plugin.settings.syncOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync Interval (minutes)").setDesc("How often to automatically sync TODOs (0 to disable)").addSlider((slider) => slider.setLimits(0, 60, 5).setValue(this.plugin.settings.syncIntervalMinutes).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.syncIntervalMinutes = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("button", {
      text: "Force Sync Now",
      cls: "mod-cta"
    }).addEventListener("click", () => {
      this.plugin.todoSynchronizer.syncTodos();
    });
  }
};

// src/todoCollector.ts
var import_obsidian2 = require("obsidian");
var TodoCollector = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Find all TODO files in the vault that match our pattern
   */
  async findAllTodoFiles() {
    const todoFiles = [];
    for (const folder of this.settings.paraFolders) {
      const files = this.app.vault.getFiles().filter(
        (file) => file.path.startsWith(folder + "/") && file.path.endsWith(".md")
      );
      for (const file of files) {
        const pathParts = file.path.split("/");
        const fileName = pathParts[pathParts.length - 1];
        const folderName = pathParts[pathParts.length - 2];
        if (fileName === `${this.settings.todoNotePrefix}${folderName}.md`) {
          todoFiles.push(file);
        }
      }
    }
    return todoFiles;
  }
  /**
   * Check if a file is a PARA TODO file based on its path
   */
  isPARATodoFile(filePath) {
    const normalizedPath = (0, import_obsidian2.normalizePath)(filePath);
    const isInParaFolder = this.settings.paraFolders.some((folder) => normalizedPath.startsWith(folder + "/"));
    if (!isInParaFolder)
      return false;
    const pathParts = normalizedPath.split("/");
    const fileName = pathParts[pathParts.length - 1];
    const folderName = pathParts[pathParts.length - 2];
    return fileName === `${this.settings.todoNotePrefix}${folderName}.md`;
  }
  /**
   * Extract General todos from the master file
   */
  extractGeneralTodos(content) {
    const lines = content.split("\n");
    const generalTodos = [];
    let inGeneralSection = false;
    for (const line of lines) {
      if (line.startsWith("# General")) {
        inGeneralSection = true;
        continue;
      }
      if (inGeneralSection && line.startsWith("#")) {
        break;
      }
      if (inGeneralSection && line.trim().startsWith("- [")) {
        generalTodos.push(line.trim());
      }
    }
    return generalTodos;
  }
  /**
   * Extract all TODO items from a file
   */
  extractTodos(content) {
    const lines = content.split("\n");
    const todos = [];
    for (const line of lines) {
      if (line.trim().startsWith("- [")) {
        todos.push(line.trim());
      }
    }
    return todos;
  }
  /**
   * Parse the master file content into a structured object
   */
  parseMasterFileContent(content) {
    const lines = content.split("\n");
    const sections = {
      General: []
    };
    let currentSection = "General";
    let currentSubsection = "";
    for (const line of lines) {
      if (line.startsWith("# ") && line !== "# General") {
        currentSection = line.substring(2).trim();
        sections[currentSection] = {};
      } else if (line.startsWith("## ")) {
        currentSubsection = line.substring(3).trim();
        if (currentSection !== "General") {
          sections[currentSection][currentSubsection] = [];
        }
      } else if (line.trim().startsWith("- [")) {
        if (currentSection === "General") {
          sections.General.push(line.trim());
        } else if (currentSubsection) {
          sections[currentSection][currentSubsection].push(line.trim());
        }
      }
    }
    return sections;
  }
};

// src/todoSynchronizer.ts
var import_obsidian3 = require("obsidian");
var TodoSynchronizer = class {
  constructor(app, settings, todoCollector) {
    this.app = app;
    this.settings = settings;
    this.todoCollector = todoCollector;
  }
  /**
   * Main function to synchronize TODOs between individual files and the master list
   */
  async syncTodos() {
    console.log("Syncing PARA TODOs...");
    const todoFiles = await this.todoCollector.findAllTodoFiles();
    const todoStructure = await this.parseTodoStructure(todoFiles);
    const masterContent = this.generateMasterTodoContent(todoStructure);
    await this.updateMasterTodoFile(masterContent);
    console.log("PARA TODOs synced successfully");
  }
  /**
   * Handle file modifications - check if it's a TODO file and sync if needed
   */
  async handleFileModification(file) {
    if (!(file instanceof import_obsidian3.TFile) || !file.path.endsWith(".md")) {
      return;
    }
    const masterPath = (0, import_obsidian3.normalizePath)(this.settings.masterTodoFilename);
    if (file.path === masterPath) {
      await this.syncFromMasterToIndividual();
      return;
    }
    const isPARATodoFile = this.todoCollector.isPARATodoFile(file.path);
    if (isPARATodoFile) {
      await this.syncTodos();
    }
  }
  /**
   * Parse TODO items from all files into a structured object
   */
  async parseTodoStructure(todoFiles) {
    const structure = {
      General: []
    };
    const masterFile = this.app.vault.getAbstractFileByPath(this.settings.masterTodoFilename);
    if (masterFile instanceof import_obsidian3.TFile) {
      const content = await this.app.vault.read(masterFile);
      const generalItems = this.todoCollector.extractGeneralTodos(content);
      structure.General = generalItems;
    }
    for (const file of todoFiles) {
      const content = await this.app.vault.read(file);
      const todos = this.todoCollector.extractTodos(content);
      const pathParts = file.path.split("/");
      const mainFolder = pathParts[0];
      const subFolder = pathParts[pathParts.length - 2];
      if (!structure[mainFolder]) {
        structure[mainFolder] = {};
      }
      structure[mainFolder][subFolder] = todos;
    }
    return structure;
  }
  /**
   * Generate the content for the master TODO file
   */
  generateMasterTodoContent(structure) {
    let content = "# General\n";
    for (const todo of structure.General) {
      content += todo + "\n";
    }
    content += "\n";
    for (const folder of this.settings.paraFolders) {
      if (structure[folder]) {
        content += `# ${folder}
`;
        for (const subFolder in structure[folder]) {
          content += `## ${subFolder}
`;
          for (const todo of structure[folder][subFolder]) {
            content += todo + "\n";
          }
          content += "\n";
        }
      }
    }
    return content;
  }
  /**
   * Create or update the master TODO file
   */
  async updateMasterTodoFile(content) {
    const masterPath = this.settings.masterTodoFilename;
    const normalizedPath = (0, import_obsidian3.normalizePath)(masterPath);
    const existingFile = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (existingFile instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(normalizedPath, content);
    }
  }
  /**
   * Sync changes from the master file back to individual TODO files
   */
  async syncFromMasterToIndividual() {
    const masterFile = this.app.vault.getAbstractFileByPath(this.settings.masterTodoFilename);
    if (!(masterFile instanceof import_obsidian3.TFile)) {
      return;
    }
    const content = await this.app.vault.read(masterFile);
    const sections = this.todoCollector.parseMasterFileContent(content);
    for (const paraFolder in sections) {
      if (paraFolder === "General")
        continue;
      for (const subFolder in sections[paraFolder]) {
        const todoFilePath = `${paraFolder}/${subFolder}/${this.settings.todoNotePrefix}${subFolder}.md`;
        const normalizedPath = (0, import_obsidian3.normalizePath)(todoFilePath);
        const todoFile = this.app.vault.getAbstractFileByPath(normalizedPath);
        if (todoFile instanceof import_obsidian3.TFile) {
          let todoContent = `# ${subFolder} TODOs

`;
          for (const todo of sections[paraFolder][subFolder]) {
            todoContent += todo + "\n";
          }
          await this.app.vault.modify(todoFile, todoContent);
        }
      }
    }
  }
};

// src/main.ts
var ParaTodoPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.syncIntervalId = null;
  }
  async onload() {
    await this.loadSettings();
    this.todoCollector = new TodoCollector(this.app, this.settings);
    this.todoSynchronizer = new TodoSynchronizer(this.app, this.settings, this.todoCollector);
    this.addRibbonIcon("checkmark", "Sync PARA TODOs", () => {
      this.todoSynchronizer.syncTodos();
    });
    this.addSettingTab(new ParaTodoSettingTab(this.app, this));
    this.addCommand({
      id: "sync-para-todos",
      name: "Sync PARA TODOs",
      callback: () => {
        this.todoSynchronizer.syncTodos();
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian4.TFile) {
          this.todoSynchronizer.handleFileModification(file);
        }
      })
    );
    if (this.settings.syncOnStartup) {
      setTimeout(() => {
        this.todoSynchronizer.syncTodos();
      }, 2e3);
    }
    this.setupSyncInterval();
  }
  setupSyncInterval() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
    if (this.settings.syncIntervalMinutes > 0) {
      const milliseconds = this.settings.syncIntervalMinutes * 60 * 1e3;
      this.syncIntervalId = window.setInterval(() => {
        this.todoSynchronizer.syncTodos();
      }, milliseconds);
    }
  }
  onunload() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.setupSyncInterval();
  }
};
